# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-01-10 03:00
from __future__ import unicode_literals

import django.contrib.postgres.fields.ranges
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(default='', max_length=109)),
                ('bank_image', models.CharField(choices=[('/media/bank_images/dbs_logo.png', 'DBS'), ('/media/bank_images/uob_logo.png', 'UOB'), ('/media/bank_images/standard_chartered_logo.png', 'Standard Charter'), ('/media/bank_images/maybank_logo.png', 'Maybank'), ('/media/bank_images/hong_leong_logo.png', 'Hong Leong Finance'), ('/media/bank_images/bea_logo.png', 'BEA'), ('/media/bank_images/ocbc-logo.png', 'OCBC'), ('/media/bank_images/posb_logo.png', 'POSB'), ('/media/bank_images/rhb_logo.png', 'RHB'), ('/media/bank_images/citibank.png', 'Citibank'), ('/media/bank_images/cimb.png', 'CIMB Bank'), ('/media/bank_images/barclays.png', 'Barclays'), ('/media/bank_images/bank_of_india.png', 'State Bank Of India'), ('/media/bank_images/bank_of_china.png', 'Bank Of China')], default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='BankRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_type', models.CharField(choices=[('Landed Property', 'Landed Property'), ('HDB', 'HDB'), ('Private Condo', 'Private Condo'), ('Executive Condo', 'Executive Condo')], default='Executive Condo', max_length=20)),
                ('construction_status', models.CharField(choices=[('Completed', 'Completed'), ('Under Construction', 'Under Construction')], default='Completed', max_length=50)),
                ('lock_in_period', models.CharField(choices=[('2 Years Locked', '2 Years Lock In Period'), ('3 Years Locked', '3 Years Lock In Period'), ('No Locked In Period', 'No Lock In Period')], default='No Locked In Period', max_length=200)),
                ('user_lock_in_preference', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=10)),
                ('interest_rates', models.FloatField()),
                ('package_priority', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)])),
                ('loan_package_min_max_range', django.contrib.postgres.fields.ranges.IntegerRangeField()),
                ('penalties', models.CharField(default='', max_length=1000)),
                ('subsidies', models.CharField(default='', max_length=1000)),
                ('additional_fees', models.CharField(default='', max_length=1000)),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank_rates.Bank')),
            ],
            options={
                'ordering': ('package_priority',),
            },
        ),
        migrations.CreateModel(
            name='BankRateType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate_type_name', models.CharField(max_length=30)),
                ('rate_type_info', models.CharField(max_length=1000)),
            ],
        ),
        migrations.AddField(
            model_name='bankrate',
            name='loan_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank_rates.BankRateType'),
        ),
    ]
