# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-12-14 02:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_rates', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankrates',
            name='max_loan_amount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='bankrates',
            name='min_loan_amount',
            field=models.IntegerField(),
        ),
    ]
