# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-12-13 08:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_rates', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankrates',
            name='bank_image',
            field=models.CharField(choices=[('127.0.0.1:8000/media/bank_images/dbs_logo.jpg', 'DBS'), ('127.0.0.1:8000/media/bank_images/uob_logo.png', 'UOB'), ('127.0.0.1:8000/media/bank_images/uob_logo.png', 'Standard Charter'), ('127.0.0.1:8000/media/bank_images/maybank_logo.png', 'Maybank'), ('127.0.0.1:8000/media/bank_images/hong_leong.jpg', 'Hong Leong Finance'), ('127.0.0.1:8000/media/bank_images/bea_logo.png', 'BEA'), ('127.0.0.1:8000/media/bank_images/ocbc_logo.png', 'OCBC'), ('127.0.0.1:8000/media/bank_images/posb_logo.png', 'POSB'), ('127.0.0.1:8000/media/bank_images/rhb_bank.png', 'RHB')], default='', max_length=200),
        ),
    ]
