# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-12-13 17:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_rates', '0002_auto_20181213_0802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankrates',
            name='bank_image',
            field=models.CharField(choices=[('/media/bank_images/dbs_logo.png', 'DBS'), ('/media/bank_images/uob_logo.png', 'UOB'), ('/media/bank_images/standard_chartered.png', 'Standard Charter'), ('/media/bank_images/maybank_logo.png', 'Maybank'), ('/media/bank_images/hong_leong_logo.png', 'Hong Leong Finance'), ('/media/bank_images/bea_logo.png', 'BEA'), ('/media/bank_images/ocbc-logo.png', 'OCBC'), ('/media/bank_images/posb_logo.png', 'POSB'), ('/media/bank_images/rhb_logo.png', 'RHB')], default='', max_length=200),
        ),
    ]
